version: '3'

services:
    db:
        image: postgres
        restart: always
        environment:
          - POSTGRES_PASSWORD=postgres
    migration:
        build: .
        command: python3 manage.py migrate
        volumes:
            - .:/usr/src/app
        depends_on:
            - db
        links:
            - db
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:8000
        links:
            - db
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        restart: always
        depends_on:
            - db
            - migration
